<?php

/**
 * @file
 * Aleph theme file.
 */

use Drupal\node\Entity\Node;

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function aleph_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  if ($route_name == 'entity.node.canonical') {
    $node = \Drupal::routeMatch()->getParameter('node');
    if ($node instanceof \Drupal\node\NodeInterface) {
      $suggestions[] = 'page__' . $node->getType();
    }
  }
}

/**
 * Implements hook_preprocess_page().
 */
function aleph_preprocess_page(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');

  if ($node && $node instanceof Node && $node->getType() == 'estudiante') {
    unset($variables['page']['content']['aleph_page_title']);
  }
}
